global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alerts/prometheus-rules.yml'

scrape_configs:
  - job_name: 'variant-c-mvc'
    static_configs:
      - targets: ['variant-c-mvc:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'variant-d-rest'
    static_configs:
      - targets: ['variant-d-rest:8081']
    metrics_path: '/actuator/prometheus'
