global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'variant-c-mvc'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'variant-d-rest'
    static_configs:
      - targets: ['localhost:8081']
    metrics_path: '/actuator/prometheus'
